// Generated by gencpp from file custom_messages/PlayResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_PLAYRESPONSE_H
#define CUSTOM_MESSAGES_MESSAGE_PLAYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_messages
{
template <class ContainerAllocator>
struct PlayResponse_
{
  typedef PlayResponse_<ContainerAllocator> Type;

  PlayResponse_()
    : play_res(0.0)  {
    }
  PlayResponse_(const ContainerAllocator& _alloc)
    : play_res(0.0)  {
  (void)_alloc;
    }



   typedef float _play_res_type;
  _play_res_type play_res;





  typedef boost::shared_ptr< ::custom_messages::PlayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::PlayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlayResponse_

typedef ::custom_messages::PlayResponse_<std::allocator<void> > PlayResponse;

typedef boost::shared_ptr< ::custom_messages::PlayResponse > PlayResponsePtr;
typedef boost::shared_ptr< ::custom_messages::PlayResponse const> PlayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::PlayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::PlayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_messages::PlayResponse_<ContainerAllocator1> & lhs, const ::custom_messages::PlayResponse_<ContainerAllocator2> & rhs)
{
  return lhs.play_res == rhs.play_res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_messages::PlayResponse_<ContainerAllocator1> & lhs, const ::custom_messages::PlayResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_messages::PlayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::PlayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::PlayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::PlayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::PlayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::PlayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::PlayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b61e27d22960a887012b295e26e4ccc";
  }

  static const char* value(const ::custom_messages::PlayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b61e27d22960a88ULL;
  static const uint64_t static_value2 = 0x7012b295e26e4cccULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::PlayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/PlayResponse";
  }

  static const char* value(const ::custom_messages::PlayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::PlayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 play_res\n"
"\n"
;
  }

  static const char* value(const ::custom_messages::PlayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::PlayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.play_res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::PlayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::PlayResponse_<ContainerAllocator>& v)
  {
    s << indent << "play_res: ";
    Printer<float>::stream(s, indent + "  ", v.play_res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_PLAYRESPONSE_H
