// Generated by gencpp from file custom_messages/Play.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_PLAY_H
#define CUSTOM_MESSAGES_MESSAGE_PLAY_H

#include <ros/service_traits.h>


#include <custom_messages/PlayRequest.h>
#include <custom_messages/PlayResponse.h>


namespace custom_messages
{

struct Play
{

typedef PlayRequest Request;
typedef PlayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Play
} // namespace custom_messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_messages::Play > {
  static const char* value()
  {
    return "926c357e5c9b841314d3b8b1f58e3abe";
  }

  static const char* value(const ::custom_messages::Play&) { return value(); }
};

template<>
struct DataType< ::custom_messages::Play > {
  static const char* value()
  {
    return "custom_messages/Play";
  }

  static const char* value(const ::custom_messages::Play&) { return value(); }
};


// service_traits::MD5Sum< ::custom_messages::PlayRequest> should match
// service_traits::MD5Sum< ::custom_messages::Play >
template<>
struct MD5Sum< ::custom_messages::PlayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_messages::Play >::value();
  }
  static const char* value(const ::custom_messages::PlayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_messages::PlayRequest> should match
// service_traits::DataType< ::custom_messages::Play >
template<>
struct DataType< ::custom_messages::PlayRequest>
{
  static const char* value()
  {
    return DataType< ::custom_messages::Play >::value();
  }
  static const char* value(const ::custom_messages::PlayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_messages::PlayResponse> should match
// service_traits::MD5Sum< ::custom_messages::Play >
template<>
struct MD5Sum< ::custom_messages::PlayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_messages::Play >::value();
  }
  static const char* value(const ::custom_messages::PlayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_messages::PlayResponse> should match
// service_traits::DataType< ::custom_messages::Play >
template<>
struct DataType< ::custom_messages::PlayResponse>
{
  static const char* value()
  {
    return DataType< ::custom_messages::Play >::value();
  }
  static const char* value(const ::custom_messages::PlayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_PLAY_H
