// Generated by gencpp from file custom_messages/PlayRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_PLAYREQUEST_H
#define CUSTOM_MESSAGES_MESSAGE_PLAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_messages
{
template <class ContainerAllocator>
struct PlayRequest_
{
  typedef PlayRequest_<ContainerAllocator> Type;

  PlayRequest_()
    : play_pose_x(0.0)
    , play_pose_y(0.0)  {
    }
  PlayRequest_(const ContainerAllocator& _alloc)
    : play_pose_x(0.0)
    , play_pose_y(0.0)  {
  (void)_alloc;
    }



   typedef float _play_pose_x_type;
  _play_pose_x_type play_pose_x;

   typedef float _play_pose_y_type;
  _play_pose_y_type play_pose_y;





  typedef boost::shared_ptr< ::custom_messages::PlayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::PlayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlayRequest_

typedef ::custom_messages::PlayRequest_<std::allocator<void> > PlayRequest;

typedef boost::shared_ptr< ::custom_messages::PlayRequest > PlayRequestPtr;
typedef boost::shared_ptr< ::custom_messages::PlayRequest const> PlayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::PlayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::PlayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_messages::PlayRequest_<ContainerAllocator1> & lhs, const ::custom_messages::PlayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.play_pose_x == rhs.play_pose_x &&
    lhs.play_pose_y == rhs.play_pose_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_messages::PlayRequest_<ContainerAllocator1> & lhs, const ::custom_messages::PlayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_messages::PlayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::PlayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::PlayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::PlayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::PlayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::PlayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::PlayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c60304461db9a9373cfa924ea61bbd9";
  }

  static const char* value(const ::custom_messages::PlayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c60304461db9a93ULL;
  static const uint64_t static_value2 = 0x73cfa924ea61bbd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::PlayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/PlayRequest";
  }

  static const char* value(const ::custom_messages::PlayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::PlayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 play_pose_x\n"
"float32 play_pose_y\n"
;
  }

  static const char* value(const ::custom_messages::PlayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::PlayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.play_pose_x);
      stream.next(m.play_pose_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::PlayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::PlayRequest_<ContainerAllocator>& v)
  {
    s << indent << "play_pose_x: ";
    Printer<float>::stream(s, indent + "  ", v.play_pose_x);
    s << indent << "play_pose_y: ";
    Printer<float>::stream(s, indent + "  ", v.play_pose_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_PLAYREQUEST_H
